### ISSUE TITLE
Cannot throw instead of return

### ISSUE THREAD

**Issue by kenn** [forge42dev/remix-toast#29]
In other words,

```ts
throw redirect('/')
```

works but

```ts
throw redirectWithError('/', 'Error!')
```

does not work. Is this a known limitation?

Using `unstable_singleFetch: true`

**Comment by AlemTuzlak** [comment]
@kenn you should await when you throw, eg. `throw await redirectWithError("/", "Error!")`

**Comment by kenn** [comment]
ooh, missed it in a plain sight 😅 thank you!
