### ISSUE TITLE
React Router 7: What is the future of this library

### ISSUE THREAD

**Issue by MattyBalaam** [forge42dev/remix-toast#30]
I’m just wondering if there are plans to migrate to RR7?

**Comment by MattyBalaam** [comment]
Haha, sorry I just noticed a v2 is out!

**Comment by AlemTuzlak** [comment]
@MattyBalaam How dare you! 🤣

**Comment by MattyBalaam** [comment]
Sorry, I should have known you would have been on top of this 🫡
